### ISSUE TITLE
Error in ohsome_post(set_endpoin...)

### ISSUE THREAD

**Issue by Hoda-Bakhshi** [GIScience/ohsome-r#8] opened 2022-07-06 10:54 UTC
Hi all

I tried to run the following code chunk to fetch the surface in the municipalities of Zurich.
#############################################
boundaries <- opq(bbox = 'zurich, switzerland') %>%
  add_osm_feature(key = 'admin_level', value = '9') %>% 
  osmdata_sf %>% unique_osmdata

#extract the actual municipalities geometrical boundaries 

municipalities <- boundaries$osm_multipolygons
municipalities_bbox=st_bbox(municipalities$geometry)
q <- ohsome_elements_count(municipalities_bbox, filter = "surface=*", time = "2018/2021/P1M")
ohsome_post(q)

q |> 
  set_time("2018/2021/P1M") |>
  ohsome_post() |>
  ggplot(aes(x = timestamp, y = value)) +
  geom_line()

library(dplyr)
q <- municipalities|> 
  mutate(id = osm_id) |>
  ohsome_elements_count(filter ="surface=*", time = "2021-06-01")

q |>
  set_endpoint(c("groupBy", "boundary"), append = TRUE) |>
  ohsome_post()

############################################
However, I get the error below:

Error in ohsome_post(set_endpoint(q, c("groupBy", "boundary"), append = TRUE)) : 
  Internal Server Error (HTTP 500).

Could you please help me to fix this issue?

**Comment by ofr1tz** [comment] 2022-07-13 10:29
Hi, 

thanks for posting this issue.

The problem appears to result from some geometries with segments of different lengths that meet at very shallow angles. This seems to cause the input geometries to have self-intersection due to rounding issues.

In order to avoid this issue, you can try simplifying the input polygons just a little bit before feeding them into ohsome. The following works for me:

```
library(dplyr)
library(sf)
library(ohsome)
library(osmdata)

boundaries <- opq(bbox = 'zurich, switzerland') |>
	add_osm_feature(key = 'admin_level', value = '9') |>
	osmdata_sf() |>
	unique_osmdata()

boundaries$osm_multipolygons |>
	mutate(id = osm_id) |>
	st_simplify(dTolerance = .05) |>
	ohsome_elements_count(filter ="surface=*", time = "2021-06-01") |>
	set_endpoint(c("groupBy", "boundary"), append = TRUE) |>
	ohsome_post()
```

**Comment by ofr1tz** [comment] 2022-07-19 08:48
Closing the issue with no fix planned. The issue is not immediately caused by the ohsome R package.

**Closed** 2022-07-19 08:48 UTC
